### ISSUE TITLE
Add folios for antiphonae ad communionem

### ISSUE THREAD

**Issue by martha-thomae** [ECHOES-from-the-Past/GABCtoMEI#4]
@elsinhadl , could you provide me the folio information for the communion antiphonas? (I have them for the other antiphonas, the Magnificats and the feriales).
I need to add this information to the metadata of the GABC files and then into the MEI files.
Thank you!

**Comment by elsinhadl** [comment]
Done. I have added them in the file "ECHOES - Final list of 100 chants". Cheers

**Comment by martha-thomae** [comment]
Thank you, @elsinhadl!

**Comment by martha-thomae** [comment]
https://docs.google.com/spreadsheets/d/11TByVRvsBOE0oY9hU-r_IszSyI8LHlrW4LF40p9vMRQ/edit#gid=0

**Comment by martha-thomae** [comment]
Fixed in 51f0921660e2fa5583ebd7bafd44fda2d6585bd5
